name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
    - name: Run compiles
      run: make test-compiles
    - name: Build pdf
      run: make kactl
    - name: Upload pdf
      uses: actions/upload-artifact@v4
      with:
        name: reference.pdf
        path: kactl.pdf
