name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: Install pdflatex
      run: sudo apt-get install texlive-latex-base texlive-latex-recommended texlive-latex-extra
    # - name: Run compiles
    #   run: make test-compiles
    # - name: Run stress tests
    #   run: make test
    - name: Build pdf
      run: make kactl
    - name: Compress
      run: zip kactl.zip kactl.pdf
    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.repository_releases_url }}
        asset_path: ./kactl.zip
        asset_name: kactl.pdf
        asset_content_type: application/pdf
      
