name: kactl

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: make kactl
      - name: Compress
        run: zip kactl.zip kactl.pdf
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./kactl.zip
          asset_name: kactl.pdf
          asset_content_type: application/pdf
